# Generated by Django 5.2.4 on 2025-07-24 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/additional_image')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.estate')),
            ],
        ),
    ]
