# Generated by Django 5.2.4 on 2025-07-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='district',
        ),
    ]
