# Generated by Django 5.2.4 on 2025-07-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=20, verbose_name='Именем пользователя'),
        ),
    ]
