# Generated by Django 5.2.4 on 2025-08-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='Включена 2FA'),
        ),
    ]
